var objeto = {"telefonos" : [
    
    {"tienda" : "Las Hadas",                "cr" : "50HDS",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422126596"},   
    {"tienda" : "Huimilpan",                "cr" : "50OHM",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422228518"},   
    {"tienda" : "Cuota",                    "cr" : "50QUO",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422253971"},   
    {"tienda" : "Pablo Cabrera",            "cr" : "50PBC",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272746684"},   
    {"tienda" : "Constitucion",             "cr" : "50OTN",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422462141"},   
    {"tienda" : "Candiles",                 "cr" : "50CDS",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422284237"},   
    {"tienda" : "Epigmenio",                "cr" : "50EPG",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422104620"},   
    {"tienda" : "Garambullo",               "cr" : "50GRM",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422189255"},   
    {"tienda" : "Arteaga",                  "cr" : "50CZS",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272712750"},   
    {"tienda" : "Moises Solana",            "cr" : "50OMS",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422229277"},   
    {"tienda" : "Salamanca",                "cr" : "50SLS",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616092646"},   
    {"tienda" : "Chabacano",                "cr" : "50CHC",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421964805"},   
    {"tienda" : "Central",                  "cr" : "50QCE",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272712720"},   
    {"tienda" : "Heliotropo",               "cr" : "50QHE",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616096349"},   
    {"tienda" : "Moctezuma",                "cr" : "50QMC",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272745277"},   
    {"tienda" : "Santa Anita",              "cr" : "50QSA",  "distrito" : "Queretaro-Norte",        "telefono" :  "4421957076"},   
    {"tienda" : "Cerro Blanco",             "cr" : "50QCB",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422482784"},   
    {"tienda" : "Libramiento Nte",          "cr" : "50DVF",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Libramiento Sur",          "cr" : "50LJI",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Campestre",                "cr" : "50QCM",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616172750"},   
    {"tienda" : "Amargura",                 "cr" : "50QAG",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422435860"},   
    {"tienda" : "2 de Abril",               "cr" : "50QAB",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616135057"},   
    {"tienda" : "Centro Sur",               "cr" : "50QCS",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422483233"},   
    {"tienda" : "Arboledas II",             "cr" : "50QAD",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616158296"},   
    {"tienda" : "Praderas",                 "cr" : "50QPA",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616177429"},  	
    {"tienda" : "Bacalar",                  "cr" : "50QBR",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422538344"},   
    {"tienda" : "Calesa",                   "cr" : "50QCA",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422483296"},   
    {"tienda" : "La Loma",                  "cr" : "50QLM",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422438078"},   
    {"tienda" : "Del Bosque",               "cr" : "50QBO",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422283957"},   
    {"tienda" : "La Estacion",              "cr" : "50QST",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151544767"},   
    {"tienda" : "Las Fuentes",              "cr" : "50FTS",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616155778"},   
    {"tienda" : "La Luz",                   "cr" : "50LUZ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151203077"},  	
    {"tienda" : "Dr Mora",                  "cr" : "50MRQ",  "distrito" : "Queretaro-Norte",        "telefono" :  "4191984018"},  	
    {"tienda" : "Sol Nino",                 "cr" : "50QSN",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422204983"},   
    {"tienda" : "Los Angeles",              "cr" : "50WAN",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422489387"},   
    {"tienda" : "Calle Ancha II",           "cr" : "50QSM",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151549093"},   
    {"tienda" : "Hercules",                 "cr" : "50HLS",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422345940"},   
    {"tienda" : "Bellavista",               "cr" : "50QBV",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422104785"},   
    {"tienda" : "Italia",                   "cr" : "50TLI",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422424292"},   
    {"tienda" : "Los Robles",               "cr" : "50QLR",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422435819"},   
    {"tienda" : "Nogalera",                 "cr" : "50ALE",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422462592"},   
    {"tienda" : "Cantera",                  "cr" : "50QCN",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272742899"},   
    {"tienda" : "San Luis de la Paz I",     "cr" : "50QSP",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "San Juan",                 "cr" : "50SJQ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272642278"},   
    {"tienda" : "Express San Carlos",       "cr" : "50SQS",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421355095"},   
    {"tienda" : "San Isidro",               "cr" : "50SWI",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422256243"},   
    {"tienda" : "Octopan",                  "cr" : "50TPK",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616088745"},   
    {"tienda" : "Deposito",                 "cr" : "50TAR",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422152936"},   
    {"tienda" : "Chapultepec",              "cr" : "50CHQ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272747383"},   
    {"tienda" : "Kamerun",                  "cr" : "50QKA",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272729667"},   
    {"tienda" : "Santa Fe",                 "cr" : "50QSF",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616086980"},   
    {"tienda" : "La Pradera",               "cr" : "50HWB",  "distrito" : "Queretaro-Norte",        "telefono" :  "4421000000"},   
    {"tienda" : "Campanario",               "cr" : "50NRI",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4611581449"},   
    {"tienda" : "El Roble",                 "cr" : "50QER",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421964079"},   
    {"tienda" : "Apaceo II",                "cr" : "50AII",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4131663429"},   
    {"tienda" : "San Luis de la Paz II",    "cr" : "50KSL",  "distrito" : "Queretaro-Norte",        "telefono" :  "4681850033"},   
    {"tienda" : "Colinas II",               "cr" : "50QCD",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422232833"},   
    {"tienda" : "Mompani",                  "cr" : "50YBD",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422986191"},   
    {"tienda" : "Lluvia ",                  "cr" : "50QLU",  "distrito" : "Queretaro-Norte",        "telefono" :  "4421990934"},   
    {"tienda" : "Americas",                 "cr" : "50ASQ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422104185"},   
    {"tienda" : "La Loma II",               "cr" : "50LLD",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422604129"},   
    {"tienda" : "Providencia",              "cr" : "50POQ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616182901"},   
    {"tienda" : "Cipreces",                 "cr" : "50CIC",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422344270"},   
    {"tienda" : "Balvanera",                "cr" : "50QBL",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421955607"},   
    {"tienda" : "Palmas",                   "cr" : "50FGH",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422136673"},   
    {"tienda" : "Insurgentes",              "cr" : "50IRN",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151548500"},   
    {"tienda" : "20 de Noviembre",          "cr" : "50VEY",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272728815"},   
    {"tienda" : "Villas del Tec",           "cr" : "50VTB",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422100396"},   
    {"tienda" : "Zapata",                   "cr" : "50ZAY",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616080502"},   
    {"tienda" : "Alameda II",               "cr" : "50AWD",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422126660"},   
    {"tienda" : "Penalty",                  "cr" : "50PEY",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422481930"},   
    {"tienda" : "Ejido",                    "cr" : "50EJW",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422423497"},   
    {"tienda" : "Acueducto",                "cr" : "50HJL",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422234884"},   
    {"tienda" : "La Cruz",                  "cr" : "50QES",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422141982"},   
    {"tienda" : "Centro",                   "cr" : "50TDM",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422128347"},   
    {"tienda" : "Abastos",                  "cr" : "50WMA",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422139224"},   
    {"tienda" : "Mat. Baco",                "cr" : "56BCO",  "distrito" : "Matadores",              "telefono" :  "4422571020"},   
    {"tienda" : "Del Parque",               "cr" : "56DLP",  "distrito" : "Matadores",              "telefono" :  "4616093551"},   
    {"tienda" : "Mat. Ghandi",              "cr" : "56GHA",  "distrito" : "Matadores",              "telefono" :  "4272642160"},   
    {"tienda" : "Hidalgo",                  "cr" : "56JHI",  "distrito" : "Matadores",              "telefono" :  "4616162327"},   
    {"tienda" : "Mat. Laurel",              "cr" : "56LEL",  "distrito" : "Matadores",              "telefono" :  "4422481520"},   
    {"tienda" : "Mat. Boulevard",           "cr" : "56MBO",  "distrito" : "Matadores",              "telefono" :  "4616137172"},   
    {"tienda" : "Mat. Candiles",            "cr" : "56MCA",  "distrito" : "Matadores",              "telefono" :  "4421350328"},   
    {"tienda" : "Mat. Jimenez",             "cr" : "56MJI",  "distrito" : "Matadores",              "telefono" :  "4616122128"},   
    {"tienda" : "Mat. Pathe",               "cr" : "56MJR",  "distrito" : "Matadores",              "telefono" :  "4422135395"},   
    {"tienda" : "Mat. Las Americas",        "cr" : "56MLA",  "distrito" : "Matadores",              "telefono" :  "4421957687"},   
    {"tienda" : "Mat. Monterrey",           "cr" : "56MMY",  "distrito" : "Matadores",              "telefono" :  "4422280927"},   
    {"tienda" : "Mat. IX",                  "cr" : "56MNU",  "distrito" : "Matadores",              "telefono" :  "4422421052"},   
    {"tienda" : "Mat. Presidentes",         "cr" : "56MPE",  "distrito" : "Matadores",              "telefono" :  "4422229205"},   
    {"tienda" : "Mat. Pedregoso",           "cr" : "56MPQ",  "distrito" : "Matadores",              "telefono" :  "4272742096"},   
    {"tienda" : "Mat. Pueblito",            "cr" : "56MPU",  "distrito" : "Matadores",              "telefono" :  "4422250168"},   
    {"tienda" : "Mat. Alamos",              "cr" : "56MQA",  "distrito" : "Matadores",              "telefono" :  "4422125462"},   
    {"tienda" : "Mat. Patines",             "cr" : "56MQP",  "distrito" : "Matadores",              "telefono" :  "4422228691"},   
    {"tienda" : "Hacienda",                 "cr" : "56MZH",  "distrito" : "Matadores",              "telefono" :  "4422151199"},   
    {"tienda" : "Penuelas II",              "cr" : "56PGJ",  "distrito" : "Matadores",              "telefono" :  "4422463156"},   
    {"tienda" : "Mat. III",                 "cr" : "56QAR",  "distrito" : "Matadores",              "telefono" :  "4422167143"},   
    {"tienda" : "Mat. La Base",             "cr" : "56QBA",  "distrito" : "Matadores",              "telefono" :  "4422223431"},   
    {"tienda" : "Mat. Capilla",             "cr" : "56QCP",  "distrito" : "Matadores",              "telefono" :  "4422150062"},   
    {"tienda" : "Mat. Don Rosco",           "cr" : "56QDR",  "distrito" : "Matadores",              "telefono" :  "4422206892"},   
    {"tienda" : "Mat. Mi General",          "cr" : "56QMG",  "distrito" : "Matadores",              "telefono" :  "4422224355"},   
    {"tienda" : "Mat. La Luz",              "cr" : "56QML",  "distrito" : "Matadores",              "telefono" :  "4421990856"},   
    {"tienda" : "Mat. IV",                  "cr" : "56QMM",  "distrito" : "Matadores",              "telefono" :  "4422142424"},   
    {"tienda" : "Mat. Ninos Heroes",        "cr" : "56QMN",  "distrito" : "Matadores",              "telefono" :  "4422154110"},   
    {"tienda" : "Mat. Panamericano",        "cr" : "56QMP",  "distrito" : "Matadores",              "telefono" :  "4482751020"},   
    {"tienda" : "Mat. Mutualismo",          "cr" : "56QMU",  "distrito" : "Matadores",              "telefono" :  "4616141174"},   
    {"tienda" : "Mat. 5 de Mayo",           "cr" : "56QMY",  "distrito" : "Matadores",              "telefono" :  "4422128683"},   
    {"tienda" : "Mat. Pipila",              "cr" : "56QPI",  "distrito" : "Matadores",              "telefono" :  "4422105221"},   
    {"tienda" : "Mat. Platon",              "cr" : "56QPN",  "distrito" : "Matadores",              "telefono" :  "4422463066"},   
    {"tienda" : "Mat. Puerto",              "cr" : "56QPO",  "distrito" : "Matadores",              "telefono" :  "4422179006"},   
    {"tienda" : "Mat.H.Col.Militar",        "cr" : "56QPT",  "distrito" : "Matadores",              "telefono" :  "4422252624"},   
    {"tienda" : "Mat. Lerma",               "cr" : "56QRL",  "distrito" : "Matadores",              "telefono" :  "4616148682"},   
    {"tienda" : "Mat. Tambor",              "cr" : "56QTM",  "distrito" : "Matadores",              "telefono" :  "4422187728"},   
    {"tienda" : "Mat. Zaragoza",            "cr" : "56QZA",  "distrito" : "Matadores",              "telefono" :  "4422127198"},   
    {"tienda" : "Mat. Oro",                 "cr" : "56RRO",  "distrito" : "Matadores",              "telefono" :  "4616090962"},   
    {"tienda" : "Mat.Santa Barbara",        "cr" : "56STB",  "distrito" : "Matadores",              "telefono" :  "4421956069"},   
    {"tienda" : "Mat. Huimilpan",           "cr" : "56WAG",  "distrito" : "Matadores",              "telefono" :  "4422226777"},   
    {"tienda" : "Mat.L.de CasaBca",         "cr" : "56WBC",  "distrito" : "Matadores",              "telefono" :  "4422223590"},   
    {"tienda" : "Mat. Bogasa",              "cr" : "56WBO",  "distrito" : "Matadores",              "telefono" :  "4422158193"},   
    {"tienda" : "Mat. Loma Bonita",         "cr" : "56WCB",  "distrito" : "Matadores",              "telefono" :  "4422184756"},   
    {"tienda" : "Mat. Hercules II",         "cr" : "56WCS",  "distrito" : "Matadores",              "telefono" :  "4422233456"},   
    {"tienda" : "Mat. Don Jorge",           "cr" : "56WDJ",  "distrito" : "Matadores",              "telefono" :  "4422227689"},   
    {"tienda" : "Mat. Esperanza",           "cr" : "56WEE",  "distrito" : "Matadores",              "telefono" :  "4422224357"},   
    {"tienda" : "Mat. Espanola",            "cr" : "56WEL",  "distrito" : "Matadores",              "telefono" :  "4422242512"},   
    {"tienda" : "Mat. Juarez",              "cr" : "56WJR",  "distrito" : "Matadores",              "telefono" :  "4272746052"},   
    {"tienda" : "Mat. La Goma",             "cr" : "56WLG",  "distrito" : "Matadores",              "telefono" :  "4422210430"},   
    {"tienda" : "Mat. La Tuna",             "cr" : "56WLT",  "distrito" : "Matadores",              "telefono" :  "4422187725"},   
    {"tienda" : "Mat. La Bota",             "cr" : "56WMB",  "distrito" : "Matadores",              "telefono" :  "4422178560"},   
    {"tienda" : "Mat. Molinos",             "cr" : "56WOO",  "distrito" : "Matadores",              "telefono" :  "4422103425"},   
    {"tienda" : "Mat. Palmas",              "cr" : "56WPA",  "distrito" : "Matadores",              "telefono" :  "4422481929"},   
    {"tienda" : "Mat. Plateros",            "cr" : "56WPL",  "distrito" : "Matadores",              "telefono" :  "4422462977"},   
    {"tienda" : "Mat. Picapiedra",          "cr" : "56WPP",  "distrito" : "Matadores",              "telefono" :  "4421990623"},   
    {"tienda" : "Mat. Estrella",            "cr" : "56WQE",  "distrito" : "Matadores",              "telefono" :  "4422143341"},   
    {"tienda" : "Mat. Plazas",              "cr" : "56WQP",  "distrito" : "Matadores",              "telefono" :  "4422169509"},   
    {"tienda" : "Mat. Balaustradas",        "cr" : "56WQV",  "distrito" : "Matadores",              "telefono" :  "4422483072"},   
    {"tienda" : "Mat. Reforma",             "cr" : "56WRF",  "distrito" : "Matadores",              "telefono" :  "4422224061"},   
    {"tienda" : "MatCorregidora I",         "cr" : "56WRG",  "distrito" : "Matadores",              "telefono" :  "4422241018"},   
    {"tienda" : "Mat. Cristal",             "cr" : "56WRL",  "distrito" : "Matadores",              "telefono" :  "4422174841"},   
    {"tienda" : "Mat. Topacio",             "cr" : "56WTO",  "distrito" : "Matadores",              "telefono" :  "4422102641"},   
    {"tienda" : "Mat. Terminal",            "cr" : "56YTL",  "distrito" : "Matadores",              "telefono" :  "4422290086"},   
    {"tienda" : "Jauregui",                 "cr" : "50WJA",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422911697"},   
    {"tienda" : "Loma Dorada",              "cr" : "50LDQ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422237193"},   
    {"tienda" : "Zacapoaxtlas",             "cr" : "50ZXT",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422437311"},   
    {"tienda" : "Carrizal",                 "cr" : "50CYL",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422152813"},   
    {"tienda" : "San Diego",                "cr" : "50ZDG",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422572314"},   
    {"tienda" : "La Cinta",                 "cr" : "50NZI",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Jacal 11",                 "cr" : "50LJK",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422162774"},  
    {"tienda" : "Girasoles",                "cr" : "50GIZ",  "distrito" : "Queretaro-Norte",        "telefono" :  "4421959600"},   
    {"tienda" : "Chichimecas",              "cr" : "50HIM",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422205936"},   
    {"tienda" : "Panteon",                  "cr" : "50WTN",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422128448"},   
    {"tienda" : "Ignacio Perez",            "cr" : "50IGP",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422152818"},   
    {"tienda" : "Camino Real",              "cr" : "50QCR",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421355246"},   
    {"tienda" : "De Letran",                "cr" : "50DTV",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422235349"},   
    {"tienda" : "Piramides",                "cr" : "50PXZ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422546288"},  
    {"tienda" : "Ghandi",                   "cr" : "50GHY",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272728856"},   
    {"tienda" : "San Roque",                "cr" : "50OQE",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422103284"},   
    {"tienda" : "Papanoa",                  "cr" : "50PAW",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422238891"},   
    {"tienda" : "Pasteur",                  "cr" : "50PTK",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422242207"},   
    {"tienda" : "Nor Poniente",             "cr" : "50NPO",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4611579033"},  
    {"tienda" : "Tampico",                  "cr" : "50PCZ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616132852"},  
    {"tienda" : "Allende",                  "cr" : "50GLL",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616130430"},  
    {"tienda" : "Socavon",                  "cr" : "50ZKV",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422346719"},   
    {"tienda" : "Libramiento",              "cr" : "50LBW",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422489023"},   
    {"tienda" : "San Angel",                "cr" : "50SGI",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422151041"},   
    {"tienda" : "Romero",                   "cr" : "50REW",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272723452"},   
    {"tienda" : "Milenio",                  "cr" : "50LNI",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422533411"},   
    {"tienda" : "Galeria",                  "cr" : "50DVG",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422484804"},   
    {"tienda" : "Malecon",                  "cr" : "50EGV",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4611595133"},  
    {"tienda" : "San Francisco",            "cr" : "50CSF",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422145748"},   
    {"tienda" : "Prol. Pino Suarez",        "cr" : "50ZUA",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422421195"},   
    {"tienda" : "La Laja",                  "cr" : "50LLJ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422153865"},   
    {"tienda" : "Parador",                  "cr" : "50DRP",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422911704"},   
    {"tienda" : "Division del Nte",         "cr" : "50CFQ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616138491"},  
    {"tienda" : "Benavente",                "cr" : "50BEV",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616088345"},  
    {"tienda" : "Brasil",                   "cr" : "50BOF",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4611607404"},  
    {"tienda" : "Iturbide",                 "cr" : "50IRB",  "distrito" : "Queretaro-Norte",        "telefono" :  "4192342856"},  
    {"tienda" : "Don Bosco",                "cr" : "50DBS",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422255544"},   
    {"tienda" : "Villa de Paris",           "cr" : "50PNJ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422144096"},   
    {"tienda" : "Macro",                    "cr" : "50KRM",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422172611"},   
    {"tienda" : "Villas Campestre",         "cr" : "50CFN",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421968293"},  
    {"tienda" : "Aculco",                   "cr" : "50UJQ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Universitario",            "cr" : "50UVR",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422342272"},   
    {"tienda" : "Lopez Mateos",             "cr" : "50MWM",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616139670"},  
    {"tienda" : "Azteca",                   "cr" : "50AZK",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422226012"},   
    {"tienda" : "Cimatario",                "cr" : "50IRC",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422124365"},   
    {"tienda" : "La Joya",                  "cr" : "50JUD",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421354648"},  
    {"tienda" : "Rivapalacio",              "cr" : "50RUQ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Azucenas",                 "cr" : "50AWZ",  "distrito" : "Queretaro-Norte",        "telefono" :  "4421991699"},   
    {"tienda" : "Morelos",                  "cr" : "50MQS",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616160392"}, 	
    {"tienda" : "La Venta",                 "cr" : "50TYI",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272746296"},   
    {"tienda" : "La Pradera II",            "cr" : "50NXQ",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Sierra Gorda",             "cr" : "50BNH",  "distrito" : "Queretaro-Norte",        "telefono" :  "4686885196"},  
    {"tienda" : "Pipila",                   "cr" : "50JKA",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151202150"}, 	
    {"tienda" : "Salitre",                  "cr" : "50QZS",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422187563"},   
    {"tienda" : "Onate",                    "cr" : "50LJG",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422120589"},   
    {"tienda" : "La Solana",                "cr" : "50KLK",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422343680"},   
    {"tienda" : "Trebol Cuota",             "cr" : "50JDH",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4131603245"},  
    {"tienda" : "Plaza Campanario",         "cr" : "50PKM",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422455349"},   
    {"tienda" : "Santa Barbara",            "cr" : "50SBZ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422259234"},  
    {"tienda" : "Gasca",                    "cr" : "50UXH",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4142734791"},   
    {"tienda" : "Juarez",                   "cr" : "50QJZ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4142734093"},   
    {"tienda" : "Amanecer",                 "cr" : "50MJD",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4421981240"},   
    {"tienda" : "Cortazar",                 "cr" : "50KWH",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616110970"},  
    {"tienda" : "Plaza Tejeda",             "cr" : "50JDA",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422280782"},   
    {"tienda" : "La Estancia",              "cr" : "50KWS",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272710806"},   
    {"tienda" : "Viterbo",                  "cr" : "50HGJ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422166619"},   
    {"tienda" : "San Felix",                "cr" : "50FLH",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4412770791"},   
    {"tienda" : "Juan Pablo II",            "cr" : "50JBP",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Imss",                     "cr" : "50TSY",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616153560"}, 	
    {"tienda" : "Mexico",                   "cr" : "50HDJ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422220530"},   
    {"tienda" : "Obrera",                   "cr" : "50OWB",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422176026"},   
    {"tienda" : "Cadereyta",                "cr" : "50KDS",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4412761214"},   
    {"tienda" : "Terminal",                 "cr" : "50HVS",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422290129"},   
    {"tienda" : "Plaza La Noria",           "cr" : "50BGU",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422774735"},   
    {"tienda" : "Casa Colorada",            "cr" : "50VFB",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422145355"},   
    {"tienda" : "Imbera",                   "cr" : "50YVQ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "San Miguelito",            "cr" : "50YBE",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151524685"},  
    {"tienda" : "Paseo Central",            "cr" : "50GJX",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272648851"},   
    {"tienda" : "Colegio Militar",          "cr" : "50HWD",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4412771618"},   
    {"tienda" : "Plaza Universidad",        "cr" : "50YBC",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272742775"},   
    {"tienda" : "El Puente",                "cr" : "56GEG",  "distrito" : "Matadores",              "telefono" :  "4422452502"},   
    {"tienda" : "San Rafael",               "cr" : "50HPF",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272748504"},   
    {"tienda" : "PIN",                      "cr" : "50QZP",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422409441"},   
    {"tienda" : "Puerta Real",              "cr" : "50YGK",  "distrito" : "Queretaro-Sur",          "telefono" :  "4423036292"},   
    {"tienda" : "Brisas",                   "cr" : "56RMB",  "distrito" : "Matadores",              "telefono" :  "4422948031"},   
    {"tienda" : "Rio",                      "cr" : "56RNB",  "distrito" : "Matadores",              "telefono" :  "4422126375"},   
    {"tienda" : "El Carmen",                "cr" : "50YFX",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111554671"},  
    {"tienda" : "Vista Hermosa",            "cr" : "50WPB",  "distrito" : "Queretaro-Norte",        "telefono" :  "4686885159"},  
    {"tienda" : "Boulevares",               "cr" : "50NSK",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422452453"},   
    {"tienda" : "Montes",                   "cr" : "50YGD",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4412770502"},   
    {"tienda" : "Ensueno",                  "cr" : "50WEU",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422426328"},   
    {"tienda" : "Cortagas",                 "cr" : "50QXD",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111600536"}, 	
    {"tienda" : "El Refugio",               "cr" : "50YNJ",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "El Sol",                   "cr" : "50YSX",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422104769"},   
    {"tienda" : "La Cima",                  "cr" : "50HPP",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Real Juriquilla",          "cr" : "50RJL",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422923170"},   
    {"tienda" : "Jacarandas",               "cr" : "50JKR",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272643325"},   
    {"tienda" : "Las Torres",               "cr" : "50QLT",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422426797"},   
    {"tienda" : "Conin",                    "cr" : "50VXW",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422774910"},   
    {"tienda" : "Ezequiel Montes II",       "cr" : "56BIB",  "distrito" : "Matadores",              "telefono" :  "4422144828"},   
    {"tienda" : "Matador Pocitos",          "cr" : "56ZJP",  "distrito" : "Matadores",              "telefono" :  "4422283571"},   
    {"tienda" : "Bicentenario",             "cr" : "50QRB",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4181828258"},  
    {"tienda" : "Monte Blanco",             "cr" : "50NZB",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422620236"},   
    {"tienda" : "La Montana",               "cr" : "50WMF",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422171062"},   
    {"tienda" : "Encinillas",               "cr" : "50ZWL",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Benito Juarez",            "cr" : "50JBZ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272746979"},   
    {"tienda" : "Mercado Escobedo",         "cr" : "50ZJE",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422123555"},   
    {"tienda" : "Agencia San Juan",         "cr" : "56WVA",  "distrito" : "Matadores",              "telefono" :  "4272713553"},   
    {"tienda" : "Canal",               	    "cr" : "50XJQ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151507567"},  
    {"tienda" : "Rancho Nuevo",             "cr" : "50FNW",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4611596638"},  
    {"tienda" : "Independencia",            "cr" : "50IYI",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4181828323"},  
    {"tienda" : "Venustiano Carranza",      "cr" : "50JRF",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4412772898"},   
    {"tienda" : "Popocatepetl II",          "cr" : "56WVD",  "distrito" : "Matadores",              "telefono" :  "4422183453"},   
    {"tienda" : "Palmillas",                "cr" : "50IYY",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Parador Turquesa",         "cr" : "50IXR",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Rayon",                    "cr" : "50BWM",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272723011"},   
    {"tienda" : "Andador Madero",           "cr" : "50UFE",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},   
    {"tienda" : "Mesones",             	    "cr" : "50UGX",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151548859"},  
    {"tienda" : "Morera",              	    "cr" : "50HKL",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4181826229"},  
    {"tienda" : "Najera",                   "cr" : "50HRF",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422125754"},   
    {"tienda" : "Presidencia",              "cr" : "50NZR",  "distrito" : "Queretaro-Norte",        "telefono" :  "4191982189"}, 	
    {"tienda" : "Asuncion",                 "cr" : "50NZW",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4142734518"},   
    {"tienda" : "Claustros",                "cr" : "50UXN",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422291771"},   
    {"tienda" : "Amealco",                  "cr" : "50EMK",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4482782280"},   
    {"tienda" : "Finsa",                    "cr" : "50FQN",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422216544"},   
    {"tienda" : "Plaza Krystal",            "cr" : "50YFS",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Palmiras",                 "cr" : "50VQP",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422456128"},   
    {"tienda" : "La Mora",                  "cr" : "50WRJ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4482789405"},   
    {"tienda" : "Petromex",                 "cr" : "50XAY",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4423101046"},   
    {"tienda" : "Euripides",                "cr" : "50EOM",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422463830"},   
    {"tienda" : "Suntuarios",               "cr" : "56FOZ",  "distrito" : "Matadores",              "telefono" :  "4422250439"},   
    {"tienda" : "La Cuesta",                "cr" : "56OUM",  "distrito" : "Matadores",              "telefono" :  "4422431792"},   
    {"tienda" : "Lazaro Cardenas",          "cr" : "50HWX",  "distrito" : "Queretaro-Sur",          "telefono" :  "4423032461"},   
    {"tienda" : "Azahares",                 "cr" : "50HZK",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4666631770"},  
    {"tienda" : "Villas deSantiago",        "cr" : "56VPX",  "distrito" : "Matadores",              "telefono" :  "4422613306"},   
    {"tienda" : "TAQ",                      "cr" : "50JNX",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422290094"},   
    {"tienda" : "Las Campanas",             "cr" : "50AUK",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422427443"},   
    {"tienda" : "UAQ",                      "cr" : "50UCW",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422153943"},   
    {"tienda" : "Cerro de la Silla",        "cr" : "50SZJ",  "distrito" : "Queretaro-Norte",        "telefono" :  "4421958253"},   
    {"tienda" : "Del Ferrocarril",          "cr" : "50BDB",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4181544366"},  
    {"tienda" : "Shopping Center",          "cr" : "50NEV",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422342568"},   
    {"tienda" : "La Griega",                "cr" : "50AIP",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422775299"},   
    {"tienda" : "Madero",                   "cr" : "50ELB",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422427365"},   
    {"tienda" : "Mission Hills",            "cr" : "50YIE",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Juriquilla StaFE",         "cr" : "50JEP",  "distrito" : "Queretaro-Norte",        "telefono" :  "4423930702"},   
    {"tienda" : "Del 57",                   "cr" : "50JPJ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422124294"},   
    {"tienda" : "Vergel",                   "cr" : "50VZL",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4142733213"},   
    {"tienda" : "Petroqro",                 "cr" : "50XAF",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4423101116"},   
    {"tienda" : "Sur Poniente",             "cr" : "50HIG",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "FrayJuniperoJuriquilla",   "cr" : "50GQW",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Bordo Blanco",             "cr" : "50IXT",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4142738245"},   
    {"tienda" : "Parque la Gloria",         "cr" : "50SVG",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},   
    {"tienda" : "Anahuac",                  "cr" : "50LKP",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Plaza Loarca",             "cr" : "50PST",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "PIQ",                      "cr" : "50HPJ",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422409662"},   
    {"tienda" : "Fray Junipero",            "cr" : "50IXM",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Loarca",                   "cr" : "50XLA",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Ind. Juarez",              "cr" : "50IAY",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422095089"},   
    {"tienda" : "Milenium",                 "cr" : "56ABD",  "distrito" : "Matadores",              "telefono" :  ""},   
    {"tienda" : "El Pocito",                "cr" : "56JGE",  "distrito" : "Matadores",              "telefono" :  "4272747314"},   
    {"tienda" : "Geoplazas",                "cr" : "50CVL",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Fovisste",                 "cr" : "50WBD",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4615983068"},  
    {"tienda" : "Mision Mariana",           "cr" : "50IBO",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421356005"},   
    {"tienda" : "Quetzales",                "cr" : "50KXG",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},   
    {"tienda" : "El Sauz Mex",              "cr" : "50MCO",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Rancho San Pedro",         "cr" : "50MLP",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Hacienda La Cruz",         "cr" : "50MLT",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Santa Sofia",              "cr" : "50IBR",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421350705"},   
    {"tienda" : "Santuarios",               "cr" : "50EDW",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422259145"},  
    {"tienda" : "Carrillo Puerto",          "cr" : "50HKV",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422104851"},   
    {"tienda" : "Ecologico",                "cr" : "50FNZ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422152556"},   
    {"tienda" : "Honda",                    "cr" : "50SLI",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Magisterial",              "cr" : "56TMM",  "distrito" : "Matadores",              "telefono" :  "4272640774"},   
    {"tienda" : "El Colorado",              "cr" : "56TLD",  "distrito" : "Matadores",              "telefono" :  "4422531507"},   
    {"tienda" : "Real del Bosque",          "cr" : "50OXY",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},   
    {"tienda" : "Tec de Monterrey",         "cr" : "50TGC",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Colinas del Sur",          "cr" : "50CVS",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422091167"},   
    {"tienda" : "Valle de Santiago",        "cr" : "50AHA",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Espuelas",                 "cr" : "50SXT",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Los Patos",                "cr" : "50MLR",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272642147"},  
    {"tienda" : "Quintanares",              "cr" : "50KWO",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Los Sauces",               "cr" : "50IXS",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422200785"},   
    {"tienda" : "El Mirador",               "cr" : "50CMN",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Camelinas",                "cr" : "50KFU",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422180979"},  
    {"tienda" : "Fuentes de Balvanera",     "cr" : "50VYY",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},  
    {"tienda" : "Las Flores",               "cr" : "50PGJ",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Comonfort",                "cr" : "50DLJ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4122208001"},  
    {"tienda" : "Mercedes Camacho",         "cr" : "50HPH",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272722247"},   
    {"tienda" : "Polotitlan",               "cr" : "50G22",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "UPQ",                      "cr" : "50S0T",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "ESTACION ANTEA",           "cr" : "50GIP",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Dos Mundos",               "cr" : "50CVM",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616118565"},  
    {"tienda" : "Cordillera",               "cr" : "50XLT",  "distrito" : "Queretaro-Norte",        "telefono" :  "4421994245"},   
    {"tienda" : "Penal",                    "cr" : "50SVW",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Paseo Marques",            "cr" : "50UGE",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Aldama",                   "cr" : "50CSY",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111602329"},  
    {"tienda" : "Villas del Meson",         "cr" : "50CDB",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422341973"},  
    {"tienda" : "Los Santos",               "cr" : "50ZAC",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Los Portales",             "cr" : "50DML",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4612151151"},  
    {"tienda" : "Bernal Centro",            "cr" : "50FNU",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Pedro Escobedo",           "cr" : "507PU",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Parque Quintana",          "cr" : "50PYQ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Presidencia",              "cr" : "56LGX",  "distrito" : "Matadores",              "telefono" :  "4272722239"},   
    {"tienda" : "Gas San Pedro",            "cr" : "50DMV",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422200177"},   
    {"tienda" : "Caseta",                   "cr" : "509HT",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Lagunillas",               "cr" : "50MEX",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Saldarriaga",              "cr" : "50SSW",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422775096"},   
    {"tienda" : "Paso Los Guzman",          "cr" : "50CPZ",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272722421"},  
    {"tienda" : "Terranova",                "cr" : "50GDV",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Via Lactea",               "cr" : "50TZT",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Paseo Dolores",            "cr" : "50RDP",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "2 de Febrero",             "cr" : "50BTI",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4666631497"},  
    {"tienda" : "Ayuntamiento",             "cr" : "50CGG",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "San Gil",                  "cr" : "50MGG",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Valle del Salitre",        "cr" : "50AGZ",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Honda",                    "cr" : "50DAN",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Sagrado Corazon",          "cr" : "50MHU",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272684405"},  
    {"tienda" : "El Molino",                "cr" : "50SMT",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4131582898"},  
    {"tienda" : "Vistha",                   "cr" : "50XLB",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "CAPRICHO",                 "cr" : "50QUG",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272641882"},   
    {"tienda" : "Los Vinedos",              "cr" : "50CLI",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Matador El Pomo",          "cr" : "56GMF",  "distrito" : "Matadores",              "telefono" :  "4422151239"},  
    {"tienda" : "MatadorGuanajuato",        "cr" : "56WLQ",  "distrito" : "Matadores",              "telefono" :  "4131660755"},   
    {"tienda" : "Nieto",                    "cr" : "50CXR",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272648117"},   
    {"tienda" : "Espiritu Santo",           "cr" : "50MMV",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272720647"},  
    {"tienda" : "MONTERREY",                "cr" : "50SEU",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422467337"},   
    {"tienda" : "Apaceo Centro",            "cr" : "50FVD",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Cd. del Sol",              "cr" : "50DNA",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Gas Quintana",             "cr" : "50GMC",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422201995"},   
    {"tienda" : "Quijay",                   "cr" : "50ZDQ",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Matador Zimapan",          "cr" : "56ARR",  "distrito" : "Matadores",              "telefono" :  "4422135461"},  
    {"tienda" : "San Andres",               "cr" : "50MNJ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4661612759"},  
    {"tienda" : "Fortuna",                  "cr" : "50KSQ",  "distrito" : "Queretaro-Norte",        "telefono" :  ""}, 	
    {"tienda" : "Estancia GEO",             "cr" : "50PJS",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},  
    {"tienda" : "Marques",                  "cr" : "50NWB",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "San Antonio",              "cr" : "50LAF",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Temixco",                  "cr" : "50DHO",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4611614961"}, 	
    {"tienda" : "Castillo",                 "cr" : "50HYI",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},  
    {"tienda" : "Uteq",                     "cr" : "50R3V",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422430139"},   
    {"tienda" : "Gallegos",                 "cr" : "50KGJ",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422253990"},  
    {"tienda" : "Velazquez",                "cr" : "50HBK",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4214730409"},   
    {"tienda" : "Puerta de Piedra",         "cr" : "50KLU",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4612208001"},  
    {"tienda" : "Matador Alcatraz",         "cr" : "56PGD",  "distrito" : "Matadores",              "telefono" :  "4422993790"},   
    {"tienda" : "Tlacote",                  "cr" : "502RB",  "distrito" : "Queretaro-Norte",        "telefono" :  ""}, 	
    {"tienda" : "16 de Septiembre",         "cr" : "50FPH",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4131660416"},  
    {"tienda" : "Gas Sombrerete",           "cr" : "50HGV",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422430635"},   
    {"tienda" : "Bosques de San Juan",      "cr" : "50J66",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "El Rosario",               "cr" : "50N31",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4421027061"},   
    {"tienda" : "Cavas",                    "cr" : "502NP",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Granito",                  "cr" : "50CD9",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Villa Napoles",            "cr" : "50GR4",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Rodeo",                    "cr" : "5060B",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "KIWI",                     "cr" : "500IC",  "distrito" : "Queretaro-Norte",        "telefono" :  ""}, 	
    {"tienda" : "Paseo Piedad",             "cr" : "50TEO",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "MegaGas",                  "cr" : "508ZL",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""}, 	
    {"tienda" : "Sonterra",                 "cr" : "50XKT",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422350627"},  
    {"tienda" : "Catania",                  "cr" : "50JV1",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},   
    {"tienda" : "Harvest",                  "cr" : "50C3U",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},   
    {"tienda" : "Gran Hacienda",            "cr" : "50VQN",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Azucenas II",              "cr" : "56NPY",  "distrito" : "Matadores",              "telefono" :  "4422603409"},   
    {"tienda" : "Matador Valcoop",          "cr" : "56BAE",  "distrito" : "Matadores",              "telefono" :  "4272712650"},   
    {"tienda" : "LIENSO",                   "cr" : "50OS7",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422250776"}, 	
    {"tienda" : "Plaza Colinas",            "cr" : "50M3N",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},  
    {"tienda" : "Jardines del Valle",       "cr" : "50Y8T",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4271052502"},   
    {"tienda" : "Juventino",                "cr" : "50NR1",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4121572425"},  
    {"tienda" : "Real de la Loma",          "cr" : "50VBM",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Matador Parres ",          "cr" : "56BTU",  "distrito" : "Matadores",              "telefono" :  "4611590216"},   
    {"tienda" : "Negreta",                  "cr" : "501T4",  "distrito" : "Queretaro-Sur",          "telefono" :  ""}, 	
    {"tienda" : "Paseo Casuarinas",         "cr" : "50GY7",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "LA PALMA",                 "cr" : "505VC",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Colinas de la piedad",     "cr" : "50C57",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422091167"},  
    {"tienda" : "Vicente Guerrero",         "cr" : "507XU",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111190240"},  
    {"tienda" : "El Colorado",              "cr" : "50O0Y",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422531625"},   
    {"tienda" : "Covarrubias",              "cr" : "50LW5",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422576686"},  
    {"tienda" : "Fatima",                   "cr" : "50J5F",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272720794"},   
    {"tienda" : "Plaza Zaragoza",           "cr" : "50AH3",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},  
    {"tienda" : "Gomez Morin",              "cr" : "50T9G",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422120250"},   
    {"tienda" : "Esnop",                    "cr" : "502G5",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Libertad",                 "cr" : "5029B",  "distrito" : "Queretaro-Norte",        "telefono" :  "4686881546"},  
    {"tienda" : "EL CARACOL",               "cr" : "50CB2",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111639361"},  
    {"tienda" : "OXXO MICROPARQUE",         "cr" : "50U79",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Parque BIcentenario",      "cr" : "50AK9",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422911469"},  
    {"tienda" : "SANTA ANA",                "cr" : "50CCS",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "Primo Verdad",             "cr" : "5027Q",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4121572329"},  
    {"tienda" : "Badajoz",                  "cr" : "507B4",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "OXXO PUERTA NAVARRA",      "cr" : "50Z5I",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Matador Calesa",           "cr" : "56FAB",  "distrito" : "Matadores",              "telefono" :  ""},  
    {"tienda" : "Matador Jardin Iturbide",  "cr" : "56HOA",  "distrito" : "Matadores",              "telefono" :  ""},   
    {"tienda" : "Matador Quintana Roo",     "cr" : "56PBH",  "distrito" : "Matadores",              "telefono" :  "4422283571"},   
    {"tienda" : "Agraria",                  "cr" : "50NQE",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422091123"},   
    {"tienda" : "Villagran",                "cr" : "50RD1",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111650122"},  
    {"tienda" : "UNIVERSO",                 "cr" : "50RHP",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},   
    {"tienda" : "Vista 2000",               "cr" : "501DZ",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422206577"},  
    {"tienda" : "Colon",                    "cr" : "501EG",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4192920011"},  
    {"tienda" : "OXXO VALLE DEL SOL",       "cr" : "50HG1",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "De la Estrella",           "cr" : "50IF4",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},   
    {"tienda" : "Angel Peralta",            "cr" : "50N9A",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},   
    {"tienda" : "Regina",                   "cr" : "50A6V",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Tiara",                    "cr" : "50FR3",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Hortencia",                "cr" : "50VP4",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4615983181"},  
    {"tienda" : "Parques",                  "cr" : "50Z3T",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422215740"},   
    {"tienda" : "Central Villagran",        "cr" : "504XL",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111650295"},  
    {"tienda" : "Sonora",                   "cr" : "5073A",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},  
    {"tienda" : "Villa Corzo",              "cr" : "507TR",  "distrito" : "Queretaro-Norte",        "telefono" :  "4191981156"},  
    {"tienda" : "Check Point",              "cr" : "50AD5",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Plaza la Vida",            "cr" : "5017W",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},  
    {"tienda" : "Industrial Celaya",        "cr" : "50KO1",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4611567936"},  
    {"tienda" : "PIO",                      "cr" : "502GF",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Fernando Diaz",            "cr" : "50MMS",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272742449"},  
    {"tienda" : "La Concepcion",            "cr" : "50Q3E",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4131582987"},  
    {"tienda" : "BANTHI",                   "cr" : "504ME",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "Real del Marques",         "cr" : "505CM",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Paseo del Bosque",         "cr" : "50Z0B",  "distrito" : "Queretaro-Sur",          "telefono" :  ""},  
    {"tienda" : "Oriente",                  "cr" : "507EG",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4482785060"},  
    {"tienda" : "Mat. Morita",              "cr" : "56MTY",  "distrito" : "Matadores",              "telefono" :  "4421935184"},  
    {"tienda" : "La Purisima",              "cr" : "501PK",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Asfaltos",                 "cr" : "507NG",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Celaya Cuota",             "cr" : "50B4P",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Rinconada",                "cr" : "50J95",  "distrito" : "Queretaro-Sjr",      	"telefono" :  ""},  
    {"tienda" : "RIO SAN JUAN",             "cr" : "50N3S",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272640749"},  
    {"tienda" : "ARAMIL",                   "cr" : "50H8K",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272721028"},  
    {"tienda" : "CORTINA",                  "cr" : "505A7",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4612160911"},  
    {"tienda" : "El Rehilete",              "cr" : "50J4R",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "PASEO DE LA JUVENTU",      "cr" : "50O2A",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111190406"},  
    {"tienda" : "Misiones",                 "cr" : "50MIO",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616175381"},  
    {"tienda" : "Alamos",                   "cr" : "50QMO",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616090482"},  
    {"tienda" : "Apaceo ",                  "cr" : "50QAP",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4131663085"},  
    {"tienda" : "Salvatierra",              "cr" : "50QSL",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4611658002"},  
    {"tienda" : "CHOPOS",                   "cr" : "505MU",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4142730707"},  
    {"tienda" : "Crespo",                   "cr" : "50QRP",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616111083"},  
    {"tienda" : "Trebol Libre",             "cr" : "50HJC",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4131603244"},  
    {"tienda" : "Carranza",                 "cr" : "50VNX",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616162491"},  
    {"tienda" : "Cascada",                  "cr" : "50G7F",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422980945"},  
    {"tienda" : "Tapiceros",                "cr" : "50VG0",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422205746"},  
    {"tienda" : "Pinos",                    "cr" : "50NJP",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616148357"},  
    {"tienda" : "Heroes",                   "cr" : "50HKZ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4181824780"},  
    {"tienda" : "Cumbres del Lago",         "cr" : "50NEZ",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "PYME",                     "cr" : "50W0D",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4426887148"},  
    {"tienda" : "VALENTINA",                "cr" : "508GU",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4181820922"},  
    {"tienda" : "Brisas",                   "cr" : "50JLV",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151858545"},  
    {"tienda" : "La Ceja",                  "cr" : "500UX",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4482785296"},  
    {"tienda" : "Sostenes Rocha",           "cr" : "50D23",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616882064"},  
    {"tienda" : "LA PENA",                  "cr" : "56KJZ",  "distrito" : "Matadores",              "telefono" :  "4271052854"},  
    {"tienda" : "Melchor Ortega",           "cr" : "50DK0",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Aragon",                   "cr" : "50JG5",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421935003"},  
    {"tienda" : "PORRON",                   "cr" : "50NV4",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422143220"},  
    {"tienda" : "Don Jose",                 "cr" : "50SU3",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422254650"},   
    {"tienda" : "Eloy Cavazos",             "cr" : "50ZL2",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422170320"},  
    {"tienda" : "FRANCO",                   "cr" : "501EX",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Plaza del Carmen",         "cr" : "50UPC",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4661612492"},  
    {"tienda" : "Platon",                   "cr" : "50MDB",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},   
    {"tienda" : "COLONIAL",                 "cr" : "504ST",  "distrito" : "Queretaro-Sur",          "telefono" :  "4192920011"},  
    {"tienda" : "Colosio",                  "cr" : "50UO4",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4111650149"},  
    {"tienda" : "Liceo",                    "cr" : "501O6",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422122722"},  
    {"tienda" : "ORVIT",                    "cr" : "50AK5",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422415115"},  
    {"tienda" : "PALOMAS",                  "cr" : "50GP0",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4271011129"},  
    {"tienda" : "OXXO METROPOLIS",          "cr" : "508HJ",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Gran victoria",            "cr" : "50V4R",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "PASEO REAL",               "cr" : "5023B",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Luis Vega",                "cr" : "502A9",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422131140"},  
    {"tienda" : "RINCON DE TAMAYO",         "cr" : "502HS",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616620380"},  
    {"tienda" : "LIAM",                     "cr" : "505T9",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "Mina II",                  "cr" : "50SU6",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4272722792"},   
    {"tienda" : "Plaza Sonterra",           "cr" : "50LQ4",  "distrito" : "Queretaro-Norte",        "telefono" :  ""},  
    {"tienda" : "OXXO UPSRJ",               "cr" : "508QG",  "distrito" : "Queretaro-Celaya",       "telefono" :  ""},  
    {"tienda" : "Matador San Agustin",      "cr" : "56KBO",  "distrito" : "Matadores",              "telefono" :  ""},   
    {"tienda" : "Reforma",                  "cr" : "50CTE",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4412760134"},  
    {"tienda" : "Mancilla",                 "cr" : "50Y90",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422122195"},  
    {"tienda" : "Circuito Jardin",          "cr" : "508YC",  "distrito" : "Queretaro-Norte",        "telefono" :  "4423258883"},   
    {"tienda" : "Circunvalacion",           "cr" : "50CIR",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422232668"},   
    {"tienda" : "Universidad",              "cr" : "50VER",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422141151"},   
    {"tienda" : "Satelite",                 "cr" : "50OSA",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422185636"},   
    {"tienda" : "Corregidora",              "cr" : "50CRR",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422232743"},   
    {"tienda" : "Arcos",                    "cr" : "50ACR",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422232640"},   
    {"tienda" : "Aeropuerto",               "cr" : "50OIC",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422240527"},   
    {"tienda" : "Tecnologico",              "cr" : "50LOG",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422154264"},   
    {"tienda" : "Hacienda",                 "cr" : "50HDA",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422169851"},   
    {"tienda" : "Carretas",                 "cr" : "50VTS",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422232321"},   
    {"tienda" : "Zaragoza",                 "cr" : "50OZG",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422169871"},   
    {"tienda" : "Capilla",                  "cr" : "50CAP",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422154502"},   
    {"tienda" : "San Miguel de Allende",    "cr" : "50QAO",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151525399"},  
    {"tienda" : "Calle Ancha I",            "cr" : "50WED",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4151524741"},  
    {"tienda" : "Quintas",                  "cr" : "50QIU",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422234989"},   
    {"tienda" : "5 de Febrero",             "cr" : "50OCF",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422179781"},   
    {"tienda" : "Arboledas",                "cr" : "50ABS",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422242250"},   
    {"tienda" : "San Jose",                 "cr" : "50QCJ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616153268"},  
    {"tienda" : "Plazas",                   "cr" : "50PZS",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422169840"},   
    {"tienda" : "Mansiones",                "cr" : "50QSI",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422157808"},  
    {"tienda" : "Constituyentes",           "cr" : "50TUY",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422237747"},   
    {"tienda" : "Juriquilla",               "cr" : "50OJU",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422340672"},   
    {"tienda" : "Alameda",                  "cr" : "50QAL",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616161020"},  
    {"tienda" : "Manuel Doblado",           "cr" : "50QDM",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616161353"},  
    {"tienda" : "Lizardi",                  "cr" : "50QLD",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616158070"},  
    {"tienda" : "Pronto La Noria",          "cr" : "50PNL",  "distrito" : "Queretaro-Sjr",      	"telefono" :  "4422215240"},   
    {"tienda" : "Exelaris",                 "cr" : "50EXQ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616139203"},  
    {"tienda" : "El Sauz",                  "cr" : "50SUQ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616158071"},  
    {"tienda" : "Fundadores",               "cr" : "50OFS",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422200701"},   
    {"tienda" : "Francisco Juarez",         "cr" : "50FJQ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616143349"},  
    {"tienda" : "Jardines",                 "cr" : "50QJC",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616161993"},  
    {"tienda" : "San Juanico",              "cr" : "50QSJ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616145669"},  
    {"tienda" : "12 de Octubre",            "cr" : "50DDQ",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616158072"},  
    {"tienda" : "Gaor",                     "cr" : "50QCZ",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422439128"},   
    {"tienda" : "Pie de La Cuesta",         "cr" : "50QPD",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422432752"},   
    {"tienda" : "Tlaloc",                   "cr" : "50QTC",  "distrito" : "Queretaro-Norte",        "telefono" :  "4421957953"},   
    {"tienda" : "Gaor II",                  "cr" : "50BQA",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422203228"},   
    {"tienda" : "Enramada",                 "cr" : "50QRM",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422126754"},   
    {"tienda" : "Hidalgo",                  "cr" : "50OHG",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422420926"},   
    {"tienda" : "La Favorita",              "cr" : "50QFV",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616162193"},  
    {"tienda" : "Naranjos",                 "cr" : "50NJS",  "distrito" : "Queretaro-Celaya",       "telefono" :  "4616158293"},  
    {"tienda" : "Tarahumaras",              "cr" : "50THM",  "distrito" : "Queretaro-Norte",        "telefono" :  "4422439831"},   
    {"tienda" : "Santo Domingo",            "cr" : "50399",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422411843"},   
    {"tienda" : "Vicario",                  "cr" : "501EH",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422416084"},  
    {"tienda" : "Madererias",               "cr" : "504V3",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422250502"},  
    {"tienda" : "6 de Diciembre",           "cr" : "5027X",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422414843"},   
    {"tienda" : "El Tanque",                "cr" : "50O66",  "distrito" : "Queretaro-Sur",          "telefono" :  "4422127198"},   
    {"tienda" : "San Mateo",                "cr" : "502E9",  "distrito" : "Queretaro-Sur",          "telefono" :  "4421967341"}  

]};